version: '3.4'

services:
  php:
    build:
      context: ./api
      target: api_php
    image: php:8.0-fpm-alpine
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
      - ./api/var:/srv/var:rw
  api:
    build:
      context: ./api
      target: api_nginx
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - "8080:80"